config/routes.rb
Rails.application.routes.draw do

resources :sessions
resources :registrations
resources :password_resets
resources :passwords

resources :registrations, only: [:new, :create]

resources :users do
  resources :messages
end
get 'line_graph/data'
delete 'logout', to: 'sessions#destroy', as: :logout


# server side charting routes
get 'charts/data', to: 'charts#data'
get 'charts/random_data'
get '/charts/chart_data', to: 'charts#chart_data'
get '/charts/chart_view', to: 'charts#chart_view'




post '/data/receive_data', to: 'data#receive_data'
post 'bets/save_burst_data'

resources :bets
get 'live_bets', to: 'bets#live_bets' # for all users bets settled=false
post '/bets/save_burst_data', to: 'bets#save_burst_data'
get '/bet_history', to: 'bets#bet_history' #for current_user all bets

post '/bets/update_burst_value', to: 'bets#update_burst_value'

get 'deposits/new'
get 'deposits/create'
resources :deposits, only: [:new, :create]

get 'withdraws/new'
resources :withdraws, only: [:new, :create]

resources :messages, only: [:index, :create]

get 'messages', to: 'messages#messages'
get '/animation', to: 'animation#show' 
get 'line_chart_example', to: 'application#line_chart_example'

get '/generate_animation', to: 'animation#generate_animation', as: 'generate_animation'
root "main#index"

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		@user = User.new # Initialize a new User instance
		@bets = Bet.where(settled: false)
		@messages = Message.order(created_at: :desc)
		@messages = Message.all # Or fetch messages from your database
		@message = Message.new #initializing an empty message object for the form
	    @bet = Bet.new
	    @bet.betid = SecureRandom.hex(6) # Generate a 6-character hexadecimal betid
  	end
end

app/views/main/index.html.erb
<%= flash[:success] %>
<%= flash[:error] %>
<body>
  <div id="container">
    <!-- Your main view -->
<img src="<%= generate_animation_path %>" alt="Animation">
    <%= render 'home/chatform'%>
    <%= render 'tables/chart'%>
    <%= render 'home/betform'%>
    
    <%= render 'tables/burst_table'%>
    <%= render 'tables/your_bets'%>

</div>

<%= javascript_include_tag 'animation_script' %>

  <!-- Include Bootstrap JS (optional) -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
      <div id="container">
        <footer>
          <p> 
          <a href="#">ZanBet BCLB no 88888 Copyright © 2023 All Rights Reserved</a></p>
        </footer>
      </div>
    </div>
</body>