config/routes.rb
Rails.application.routes.draw do

resources :sessions
resources :registrations
resources :password_resets
resources :passwords

resources :registrations, only: [:new, :create]

resources :users do
  resources :messages
end
get 'line_graph/data'
delete 'logout', to: 'sessions#destroy', as: :logout


# server side charting routes
get 'charts/data', to: 'charts#data'
get 'charts/random_data'
get '/charts/chart_data', to: 'charts#chart_data'
get '/charts/chart_view', to: 'charts#chart_view'




post '/data/receive_data', to: 'data#receive_data'
post 'bets/save_burst_data'

resources :bets
get 'live_bets', to: 'bets#live_bets' # for all users bets settled=false
post '/bets/save_burst_data', to: 'bets#save_burst_data'
get '/bet_history', to: 'bets#bet_history' #for current_user all bets

post '/bets/update_burst_value', to: 'bets#update_burst_value'

get 'deposits/new'
get 'deposits/create'
resources :deposits, only: [:new, :create]

get 'withdraws/new'
resources :withdraws, only: [:new, :create]

resources :messages, only: [:index, :create]

get 'messages', to: 'messages#messages'
get '/animation', to: 'animation#show' 
get 'line_chart_example', to: 'application#line_chart_example'

get '/generate_animation', to: 'animation#generate_animation', as: 'generate_animation'
root "main#index"

end

app/models/withdraw.rb
class Withdraw < ApplicationRecord
end

app/controllers/withdraw_controller.rb
class WithdrawController < ApplicationController
	def new
    @withdraw = Withdraw.new
  end

  def create
    @withdraw = current_user.withdraw.build(withdraw_params)
    if @withdraw.save
      #Create the Withdrawal handling here
      # Call the M-Pesa API to initiate the withdrawal here
      # Handle the payment response and update the user's account balance
      flash[:success] = 'Withdraw successful'
      redirect_to root_path
    else
      flash[:error] = 'Withdraw failed'
      render :new
    end
  end

  private

  def withdraw_params
    params.require(:withdraw).permit(:amount)
  end
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/withdraw/new.html.erb
<!-- app/views/deposits/new.html.erb -->
<div id ="bet-container">
     <div class="card" style="width: 100%">
        <div class="card-header">
           <p class="card-title">Withdraw To Mpesa</h5p>
            </div>
              <div class="card-body">
                <%= form_for @withdraw, url: new_withdraw_path do |f| %>
                  <div class="form-group">
                        <!-- Pre-fill the phone_number field with the user's phone number -->
                    <%= hidden_field_tag :phone_number, current_user.phone_number %>

                    <%= f.label :amount, 'Withdraw Amount',required: true %>
                    <%= f.number_field :amount, class: 'form-control', step: '1', required: true%>
                  </div>
              <%= f.submit 'Withdraw', class: 'btn btn-primary' %>
            <% end %>
      </div>
    </div>
  </div>
</div>