config/routes.rb
Rails.application.routes.draw do

resources :sessions
resources :registrations
resources :password_resets
resources :passwords

resources :registrations, only: [:new, :create]

resources :users do
  resources :messages
end
get 'line_graph/data'
delete 'logout', to: 'sessions#destroy', as: :logout


# server side charting routes
get 'charts/data', to: 'charts#data'
get 'charts/random_data'
get '/charts/chart_data', to: 'charts#chart_data'
get '/charts/chart_view', to: 'charts#chart_view'




post '/data/receive_data', to: 'data#receive_data'
post 'bets/save_burst_data'

resources :bets
get 'live_bets', to: 'bets#live_bets' # for all users bets settled=false
post '/bets/save_burst_data', to: 'bets#save_burst_data'
get '/bet_history', to: 'bets#bet_history' #for current_user all bets

post '/bets/update_burst_value', to: 'bets#update_burst_value'

get 'deposits/new'
get 'deposits/create'
resources :deposits, only: [:new, :create]

get 'withdraws/new'
resources :withdraws, only: [:new, :create]

resources :messages, only: [:index, :create]

get 'messages', to: 'messages#messages'
get '/animation', to: 'animation#show' 
get 'line_chart_example', to: 'application#line_chart_example'

get '/generate_animation', to: 'animation#generate_animation', as: 'generate_animation'
root "main#index"

end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
  before_action :authenticate_user!

end

app/controllers/deposits_controller.rb
# app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  def new
    @deposit = Deposit.new
  end

  def create
    @deposit = current_user.deposits.build(deposit_params)
    if @deposit.save
      # Call the M-Pesa API to initiate the payment here
      # Handle the payment response and update the user's account balance
      flash[:success] = 'Deposit successful'
      redirect_to root_path
    else
      flash[:error] = 'Deposit failed'
      render :new
    end
  end

  private

  def deposit_params
    params.require(:deposit).permit(:amount)
  end
end

app/views/deposits/_modal.html.erb
<div class="modal fade" id="depositModal" tabindex="-1" role="dialog" aria-labelledby="depositModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content" style="background-color: dark;">
      <div class="modal-header">
        <h5 class="modal-title" id="depositModalLabel">deposit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center"> <!-- Added text-center class for centering -->
      <% if user_signed_in? %>
        <%= form_with model: @user, url: deposits_path do |form| %>
          <% if form.object.errors.any? %>
            <% form.object.errors.full_messages.each do |message| %>
              <div><%= message %></div>
            <% end %>
          <% end %>

          <div>
            <%= hidden_field_tag :phone_number,current_user.phone_number %>
              <br>
            <%= form.label :amount %><br>
            <%= form.text_field :amount %>
          </div>
          <br>
          <div>
            <%= form.submit "deposit" %>
          </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/deposits/create.html.erb
<h1>Deposits#create</h1>
<p>Find me in app/views/deposits/create.html.erb</p>

app/views/deposits/new.html.erb
<!-- app/views/deposits/new.html.erb -->
<div class="modal">
 -->  <div id ="bet-container">
   <div class="card" style="width: 100%">
      <div class="card-header">
         <p class="card-title">Deposit From Mpesa</h5p>
      </div>
        <div class="card-body">
          <%= form_for @deposit, url: deposits_path, method: "post", remote: true do |f| %>
            <div class="form-group">
                  <!-- Pre-fill the phone_number field with the user's phone number -->
             <!-- Pre-fill the phone_number field with the user's phone number -->
              <%= f.label :phone_number,current_user.phone_number %>
              <br>
              <%= f.label :amount, 'Deposit Amount',required: true %>
              <%= f.number_field :amount, class: 'form-control', step: '1', required: true%>
            </div>
            <%= f.submit 'Deposit', class: 'btn btn-primary' %> 
            <!-- <%= link_to "Deposit", "#", data: {controller: "modals", action: "modals#close"},class: "close" %>-->
          <% end %>
        </div>
      <!-- </div> -->
     </div>
    </div>
</div>
<% end %>